package com.kynstore.inventory.util

data class AppStrings(
    val languageName: String,
    val chooseLanguageTitle: String,
    val appTitle: String,
    val appSubtitle: String,
    val offlineBadge: String,
    val securityHeader: String,
    val guarantee1Title: String,
    val guarantee1Desc: String,
    val guarantee2Title: String,
    val guarantee2Desc: String,
    val guarantee3Title: String,
    val guarantee3Desc: String,
    val agreementHeading: String,
    val agreementCheckLabel: String,
    val termsLink: String,
    val privacyLink: String,
    val startButton: String,
    val readySubtitle: String,
    val notAgreedSubtitle: String,
    val warningTitle: String,
    val warningText: String,
    val agreeAndContinue: String,
    val backButton: String,
    val prepTitle: String,
    val prepStep1: String,
    val prepStep2: String,
    val prepStep3: String,
    val prepEncryptedBadge: String,

    // Main App Navigation & Headers
    val navPosTitle: String,
    val navInventoryTitle: String,
    val switchLanguageMenu: String,
    val termsAndPrivacyMenu: String,
    val syncRefreshMenu: String,

    // Add Action Buttons
    val addLabel: String
) {
    companion object {
        fun forLanguage(language: AppLanguage): AppStrings = when (language) {
            AppLanguage.TAGALOG -> AppStrings(
                languageName = "Tagalog (Filipino)",
                chooseLanguageTitle = "Pumili ng Wika / Language",
                appTitle = "KYN Store",
                appSubtitle = "Tindahan POS & Imbentaryo",
                offlineBadge = "100% Offline Mode • Ligtas sa Device",
                securityHeader = "Pangangalaga sa Datos ng Tindahan",
                guarantee1Title = "Walang Cloud / 100% On-Device",
                guarantee1Desc = "Lahat ng paninda, presyo, at benta ay nakaimbak lamang sa sarili mong telepono. Walang data na lumalabas o umaabot sa cloud.",
                guarantee2Title = "Protektado sa Bawat Update",
                guarantee2Desc = "Hindi kailanman mabubura ang iyong imbentaryo tuwing may bagong bersyon o update ang app. Buo at protektado ang iyong mga tala.",
                guarantee3Title = "Protektado Laban sa Breaches",
                guarantee3Desc = "Nakatago ang lahat ng internal database IDs at detalye. Zero telemetry, walang ad tracking, at walang third-party leaks.",
                agreementHeading = "Pagsang-ayon bago magsimula:",
                agreementCheckLabel = "Nabasa at sumasang-ayon ako sa mga tuntunin at patakaran sa kaligtasan ng datos:",
                termsLink = "Mga Tuntunin",
                privacyLink = "Patakaran sa Privacy",
                startButton = "SIMULAN ANG TINDAHAN",
                readySubtitle = "Nakahanda nang buksan ang tindahan",
                notAgreedSubtitle = "Kailangan munang sumang-ayon upang makapasok",
                warningTitle = "Kinakailangan ang Pagsang-ayon",
                warningText = "Upang maprotektahan ang iyong tindahan at masiguro ang 100% on-device offline storage, kailangan munang lagyan ng tsek ang pagsang-ayon sa Mga Tuntunin at Patakaran sa Privacy bago makapasok sa application.",
                agreeAndContinue = "Sumang-ayon at Magpatuloy",
                backButton = "Bumalik",
                prepTitle = "Inihahanda ang Tindahan...",
                prepStep1 = "Sinusuri ang lokal na database sa device...",
                prepStep2 = "Sinusuri ang integridad at proteksyon ng data sa offline storage...",
                prepStep3 = "Inihahanda ang POS Cashier at Barcode Scanner...",
                prepEncryptedBadge = "100% Offline • Naka-encrypt sa Device Storage",
                navPosTitle = "Tindahan POS",
                navInventoryTitle = "Imbentaryo",
                switchLanguageMenu = "Palitan ang Wika (Language)",
                termsAndPrivacyMenu = "Mga Tuntunin at Privacy Policy",
                syncRefreshMenu = "I-Sync / I-Refresh ang Tindahan",
                addLabel = "Dagdag"
            )

            AppLanguage.ENGLISH -> AppStrings(
                languageName = "English",
                chooseLanguageTitle = "Choose Language / Pumili ng Wika",
                appTitle = "KYN Store",
                appSubtitle = "Store POS & Inventory System",
                offlineBadge = "100% Offline Mode • Secure on Device",
                securityHeader = "Store Data Protection & Privacy",
                guarantee1Title = "No Cloud / 100% On-Device",
                guarantee1Desc = "All products, prices, and sales records are stored solely inside your phone. No data ever leaves or uploads to any cloud servers.",
                guarantee2Title = "Protected Across Updates",
                guarantee2Desc = "Your inventory will never be wiped or erased when updating the app. All records and stock counts remain 100% intact.",
                guarantee3Title = "Protected Against Breaches",
                guarantee3Desc = "All internal database IDs and technical details are hidden. Zero telemetry, no ad tracking, and zero data leakage.",
                agreementHeading = "Agreement before proceeding:",
                agreementCheckLabel = "I have read and agree to the terms and data privacy policies:",
                termsLink = "Terms & Conditions",
                privacyLink = "Privacy Policy",
                startButton = "START STORE POS",
                readySubtitle = "Ready to launch store POS",
                notAgreedSubtitle = "Agreement required before entering",
                warningTitle = "Agreement Required",
                warningText = "To protect your store and guarantee 100% on-device offline storage, you must check the agreement box for Terms and Privacy Policy before proceeding into the application.",
                agreeAndContinue = "Agree & Continue",
                backButton = "Go Back",
                prepTitle = "Preparing Store POS...",
                prepStep1 = "Checking local database on device...",
                prepStep2 = "Verifying data integrity and offline storage protection...",
                prepStep3 = "Preparing POS Cashier and Barcode Scanner...",
                prepEncryptedBadge = "100% Offline • Encrypted in Device Storage",
                navPosTitle = "Store POS",
                navInventoryTitle = "Inventory Stock",
                switchLanguageMenu = "Change Language",
                termsAndPrivacyMenu = "Terms & Privacy Policy",
                syncRefreshMenu = "Sync / Refresh Database",
                addLabel = "Add"
            )

            AppLanguage.CEBUANO -> AppStrings(
                languageName = "Bisaya (Cebuano)",
                chooseLanguageTitle = "Pagpili og Pinulongan / Language",
                appTitle = "KYN Store",
                appSubtitle = "Tindahan POS & Imbentaryo",
                offlineBadge = "100% Offline Mode • Luwas sa Device",
                securityHeader = "Proteksyon sa Data sa Tindahan",
                guarantee1Title = "Walay Cloud / 100% Sa Device Lamang",
                guarantee1Desc = "Tanan nga baligya, presyo, ug halin gitipigan lang sa imong telepono. Walay data nga mogawas o maabot sa cloud.",
                guarantee2Title = "Protektado sa Matag Update",
                guarantee2Desc = "Dili gayod mapapas ang imong imbentaryo kung mag-update ang app. Kompleto ug protektado ang tanang lista.",
                guarantee3Title = "Protektado Batok sa Breaches",
                guarantee3Desc = "Nakatago ang tanang internal database details. Walay tracking, walay ads, ug walay data leaks.",
                agreementHeading = "Pagsugot sa dili pa magsugod:",
                agreementCheckLabel = "Nabasa ug nisugot ko sa mga lagda ug patakaran sa proteksyon sa datos:",
                termsLink = "Mga Lagda",
                privacyLink = "Patakaran sa Privacy",
                startButton = "SUGDI ANG TINDAHAN",
                readySubtitle = "Andam na nga ablihan ang tindahan",
                notAgreedSubtitle = "Kinahanglan una nga mosugot sa dili pa mosulod",
                warningTitle = "Gikinahanglan ang Pagsugot",
                warningText = "Aron mapanalipdan ang imong tindahan ug masiguro ang 100% offline storage, kinahanglan una nga tsek-an ang pagsugot sa Mga Lagda ug Privacy Policy sa dili pa mosulod.",
                agreeAndContinue = "Mosugot ug Mopadayon",
                backButton = "Balik",
                prepTitle = "Giandam ang Tindahan...",
                prepStep1 = "Gisusi ang lokal nga database sa device...",
                prepStep2 = "Gisusi ang kaluwasan ug proteksyon sa data sa offline storage...",
                prepStep3 = "Giandam ang POS Cashier ug Barcode Scanner...",
                prepEncryptedBadge = "100% Offline • Luwas sa Device Storage",
                navPosTitle = "POS Tindahan",
                navInventoryTitle = "Imbentaryo",
                switchLanguageMenu = "Ilisi ang Pinulongan (Language)",
                termsAndPrivacyMenu = "Mga Lagda ug Privacy Policy",
                syncRefreshMenu = "I-Sync / I-Refresh ang Tindahan",
                addLabel = "Dagdag"
            )
        }
    }
}
